import { type Property } from '@/components/PropertyCard'

// Enhanced Sample property data with operational discounts and availability states
export const SAMPLE_PROPERTIES: Property[] = [
  {
    id: '1',
    uniqueId: 'PR-101',
    isFeatured: true,
    price: 8500,
    discountPrice: 6500, // Triggers "1st Month Offer" badge
    type: '2BHK Flat',
    category: 'Residential' as const,
    location: 'Yogikuti, Butwal',
    area: 'Butwal',
    floorLevel: '2nd Floor',
    parkingType: 'Bikes & Cars',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=450&fit=crop',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=450&fit=crop',
      'https://images.unsplash.com/photo-1516455207990-7a41e440d268?w=600&h=450&fit=crop',
    ],
    beds: 2,
    baths: 1,
    hasParking: true,
    waterType: '24/7',
    waterIncluded: true,
    electricityMeterType: 'Individual',
    bathroomType: 'Attached',
    furnishingStatus: 'Semi-Furnished',
    description: 'Spacious 2BHK flat with modern amenities, located in a prime area with easy access to markets and transportation. Recently renovated with premium finishings.',
    hasVideo: true,
    comments: 12,
    availabilityStatus: 'Available Now', // Triggers solid Mint Green badge
  },
  {
    id: '2',
    uniqueId: 'PR-102',
    isFeatured: false,
    price: 5500,
    type: '1BHK Flat',
    category: 'Residential' as const,
    location: 'Bhairahawa City',
    area: 'Bhairahawa',
    floorLevel: 'Ground Floor',
    parkingType: 'Bikes Only',
    images: [
      'https://images.unsplash.com/photo-1542718323-2f41cc844e5e?w=600&h=450&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=450&fit=crop',
    ],
    beds: 1,
    baths: 1,
    hasParking: false,
    waterType: 'Alternate Days',
    waterIncluded: true,
    electricityMeterType: 'Shared',
    bathroomType: 'Shared',
    furnishingStatus: 'Unfurnished',
    description: 'Cozy 1BHK flat perfect for couples or single professionals. Well-lit rooms with modern finishings and good cross-ventilation.',
    hasVideo: false,
    comments: 8,
    availabilityStatus: 'Moving Out Soon', // Triggers "Moving Soon" amber/orange badge
  },
  {
    id: '3',
    uniqueId: 'PR-103',
    isFeatured: false,
    price: 3500,
    discountPrice: 2500, // Triggers "1st Month Offer" badge
    type: 'Single Room',
    category: 'Residential' as const,
    location: 'Yogikuti, Butwal',
    area: 'Butwal',
    floorLevel: '1st Floor',
    parkingType: 'Bikes Only',
    images: [
      'https://images.unsplash.com/photo-1634995066007-e60cf2b91bb3?w=600&h=450&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=450&fit=crop',
    ],
    beds: 1,
    baths: 1,
    hasParking: false,
    waterType: '24/7',
    waterIncluded: true,
    electricityMeterType: 'Individual',
    bathroomType: 'Attached',
    furnishingStatus: 'Furnished',
    description: 'Affordable single room with attached bathroom and a small balcony. Ideal for students or job seekers. Building has good security.',
    hasVideo: true,
    comments: 6,
    availabilityStatus: 'Available Now',
  },
  {
    id: '4',
    uniqueId: 'PR-104',
    isFeatured: true,
    price: 12000,
    type: '2BHK Flat',
    category: 'Residential' as const,
    location: 'Main Road, Butwal',
    area: 'Butwal',
    floorLevel: '3rd Floor',
    parkingType: 'Bikes & Cars',
    images: [
      'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&h=450&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=450&fit=crop',
      'https://images.unsplash.com/photo-1516455207990-7a41e440d268?w=600&h=450&fit=crop',
    ],
    beds: 2,
    baths: 2,
    hasParking: true,
    waterType: '24/7',
    waterIncluded: true,
    electricityMeterType: 'Individual',
    bathroomType: 'Attached',
    furnishingStatus: 'Furnished',
    description: 'Luxury 2BHK flat with premium finishings and excellent ventilation. Close to all amenities including restaurants, shopping mall, and public transport.',
    hasVideo: true,
    comments: 18,
    availabilityStatus: 'Rented', // Triggers dark slate overlay state
  },
  {
    id: '5',
    uniqueId: 'PR-105',
    isFeatured: false,
    price: 7000,
    discountPrice: 5000, // Triggers "1st Month Offer" badge
    type: 'Office Spaces',
    category: 'Commercial' as const,
    location: 'Market Square, Bhairahawa',
    area: 'Bhairahawa',
    images: [
      'https://images.unsplash.com/photo-1606126613408-eca07e646917?w=600&h=450&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=450&fit=crop',
    ],
    beds: 0,
    baths: 1,
    hasParking: true,
    squareFootage: 1200,
    waterType: 'N/A',
    waterIncluded: false,
    electricityMeterType: 'Shared',
    bathroomType: 'Shared',
    furnishingStatus: 'Unfurnished',
    description: 'Prime commercial office space in busy market area. Perfect for retail or small business setup. High foot traffic area with excellent visibility.',
    hasVideo: false,
    comments: 5,
    availabilityStatus: 'Available Now',
  },
  {
    id: '6',
    uniqueId: 'PR-106',
    isFeatured: false,
    price: 6500,
    type: '1BHK Flat',
    category: 'Residential' as const,
    location: 'Nepalgunj Road, Yogikuti',
    area: 'Yogikuti',
    floorLevel: '4th Floor',
    parkingType: 'Bikes & Cars',
    images: [
      'https://images.unsplash.com/photo-1512672015474-a64af1aa331c?w=600&h=450&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=450&fit=crop',
    ],
    beds: 1,
    baths: 1,
    hasParking: true,
    waterType: '24/7',
    waterIncluded: true,
    electricityMeterType: 'Individual',
    bathroomType: 'Attached',
    furnishingStatus: 'Semi-Furnished',
    description: 'Modern 1BHK with contemporary design. Located near college campus and shopping centers. Great locality with vibrant nightlife.',
    hasVideo: true,
    comments: 10,
    availabilityStatus: 'Available Now',
  },
  {
    id: '7',
    uniqueId: 'PR-107',
    isFeatured: true,
    price: 15000,
    discountPrice: 12500, // Triggers "1st Month Offer" badge
    type: 'Commercial Building',
    category: 'Commercial' as const,
    location: 'Butwal Market, Butwal',
    area: 'Butwal',
    images: [
      'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&h=450&fit=crop',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=450&fit=crop',
    ],
    beds: 0,
    baths: 2,
    hasParking: true,
    squareFootage: 2500,
    waterType: '24/7',
    waterIncluded: false,
    electricityMeterType: 'Individual',
    bathroomType: 'Attached',
    furnishingStatus: 'Unfurnished',
    description: 'Modern commercial building with multiple floors. Ideal for corporate offices, educational institutions, or large retail operations. Near main commercial hub.',
    hasVideo: true,
    comments: 14,
    availabilityStatus: 'Available Now',
  },
]